version: '3.8'

services:
# App container
  app:
    image: django:latest
    container_name: "app-{{.Task.Slot}}"
    env_file:
      - deployment.env
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==worker"
    secrets:
      - source: my_password
        target: my_password
        uid: '999'
        gid: '0'
        mode: 0440
    networks:
      mynet:
        ipv4_address: 172.10.0.10
# uWSGI Container
  app-proxy:
    image: app-proxy:latest
    container_name: uwsgi-proxy
    deploy:
      endpoint_mode: vip
      constraints:
        - "node.role==manager"
    networks:
      mynet:
        ipv4_address: 172.10.0.15
# Nginx Container
  www-proxy:
    depends_on:
      - django
    image: www-proxy:latest
    container_name: nginx-proxy
    deploy:
      endpoint_mode: vip
      constraints:
        - "node.role==manager"
    networks:
      mynet:
        ipv4_address: 172.10.0.30
# DB container
  db:
    image: postgres:11.3
    container_name: "db-{{.Task.Slot}}"
    env_file:
      - deployment.env
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    networks:
      mynet:
        ipv4_address: 172.10.0.20
    volumes:
      - type: volume
        source: polls_vol
        target: /var/lib/postgres/data

configs:
  nginx_config:
    file: configs/flask_lb_nginx.conf

secrets:
  my_password:
    file: secrets/my_password.txt

volumes:
  polls_vol:
networks:
  mynet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "172.10.0.0/24"
