version: '3.8'

services:
# App container
  app:
    image: app:latest
    hostname: "app-{{.Task.Slot}}"
    env_file:
      - deployment.env
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==worker"
    networks:
      - proxy_net
      - db_net
# Nginx Container
  www-proxy:
    image: www-proxy:latest
    hostname: nginx-proxy
    deploy:
      mode: global
    ports:
      - target: 8000
        published: 8000
        mode: host
    configs:
      - source: proxy_conf
        target: /etc/nginx/conf.d/mysite_nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - proxy_net
# DB container
  db:
    image: postgres:11.3
    hostname: "db-{{.Task.Slot}}"
    env_file:
      - deployment.env
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    networks:
      - db_net
    volumes:
      - type: volume
        source: polls_vol
        target: /var/lib/postgres/data

configs:
  proxy_conf:
    file: configs/mysite_nginx_in_swarm.conf

secrets:
  my_password:
    file: secrets/my_password.txt

volumes:
  polls_vol:
networks:
  db_net:
    driver: overlay
    name: galera_net
    attachable: true
  proxy_net:
    driver: overlay
