version: '3.8'

services:
# App container
  app:
    image: app:latest
    hostname: "app-{{.Task.Slot}}"
    env_file:
      - ./db_params.env
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - proxy_net
      - db_net
# Nginx Container
  www-proxy:
    image: www-proxy:latest
    hostname: nginx-proxy
    deploy:
      mode: global
    ports:
      - target: 8000
        published: 8000
        mode: host
    configs:
      - source: proxy_conf
        target: /etc/nginx/conf.d/mysite_nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - proxy_net
# DB container
  galera:
    image: pythonincontainers/galera:latest
    env_file:
      - ./db_params.env
    networks:
      - db_net
    deploy:
      mode: global
    environment:
      SERVICE_NAME: django-polls_galera

configs:
  proxy_conf:
    file: configs/mysite_nginx_in_swarm.conf

secrets:
  my_password:
    file: secrets/my_password.txt

volumes:
  polls_vol:
networks:
  db_net:
    driver: overlay
    name: db_net
    attachable: true
  proxy_net:
    driver: overlay
