version: '3.8'

services:
# App container
  django:
    image: django:latest
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.django
# uWSGI Container
  app-proxy:
    image: app-proxy:latest
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.uwsgi
# Nginx Container
  www-proxy:
    depends_on:
      - django
    image: www-proxy:latest
    build:
      context: ./django-polls
      dockerfile: Dockerfile.nginx
      args:
        BASE_IMAGE: django:latest
    entrypoint: /bin/true
# DB container
  app:
    depends_on:
      - app-proxy
    image: app:latest
    build:
      context: ./django-polls
      dockerfile: Dockerfile.app
      args:
        BASE_IMAGE: app-proxy:latest
    entrypoint: /bin/true
