version: "3.8"

services:
  db:
    image: postgres:11.3
    networks:
      - polls_net
    volumes:
      - polls_vol:/var/lib/postgresql/data
    env_file:
      - ./Configs/db.env

  app1:
    image: app1:latest
    networks:
      - polls_net
    env_file:
      - ./Configs/db.env

  proxy:
    image: www-proxy:latest
    networks:
      - polls_net
    ports:
      - "8000:8000"

networks:
  polls_net:
volumes:
  polls_vol:
